manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/josishmail
  projects:
    - name: zmk
      remote: zmk
      revision: support-trackball
      import: app/west.yml
  self:
    path: config
